### ISSUE TITLE
Translate? What You Doin?

### ISSUE THREAD

**Issue by ollybritton** [ollybritton/BoiLang#1]
*Wow? A Self Issue???*

When you try and translates stuff, it goes weird. Fix it. Now.

**Comment by ollybritton** [comment]
will do

**Comment by ollybritton** [comment]
thanks m8

**Comment by ollybritton** [comment]
youre welcome

**Comment by charliebritton** [comment]
@ollybritton hi

**Comment by charliebritton** [comment]
@ollybritton its not like were brothers or anything

**Comment by charliebritton** [comment]
#2 was also bad

**Comment by ollybritton** [comment]
Note To Self: It's the loops that don't work you idiot.
